### ISSUE TITLE
Extend CurrentDateTime Generator

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#51]
**Is your feature request related to a problem? Please describe.**
Extend with paramenter "timezone"

**Comment by vbergmann2** [comment]
CurrentDateTimeGenerator generates objects of type java.util.Date, which represent a point in time by milliseconds since Jan 1, 1970, 0:00 UTC (epoch value). Any code which would associate this object with a timezone is deprecated. According to the specification, any timezone features shall be applied using the Calendar class. 

One could state that it is useful to generate Date objects for another timezone by checking their local time value and generating a Date object that represents the epoch value that this time value would have in the UTC timezone. This would break the contract of the class java.util.Date and may cause 
1. confusion among users which are familiar with the Java classes
2. unintended side effects we are not yet aware of and trouble by breaking user code when they need to be addressed

As a compromise, I will implement a CurrentZonedDateTimeGenerator which generates ZonedDateTime objects of the new Java Time API, supporting a zoneId attribute, but leave this topic open tentatively in case there are strong arguments for timezone support in CurrentDateTimeGenerator too.

**Comment by vbergmann2** [comment]
Thank you for the proposal. We analyzed it and created related generators to Benerator release 3.0.0 (which will be provided within a few days). There will be a CurrentZonedDateTimeGenerator and a general ZonedDateTimeGenerator. they reflect the capabilities of the existing generators (CurrentDateTimeGenerator and DateTimeGenerator) with an additional 'zone' property.
